[package]
name    = "life"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]

[dependencies]
pxl  = {path = "../.."}
rand = "0.5.0"

[build-dependencies]
pxl  = {path = "../.."}
walkdir = "2.0.0"
